import type { SafeStorage } from "./storage";
import { normalizeDistinctId } from "../shared/ids";
import { uuidv4 } from "../shared/uuid";

const ANONYMOUS_ID_KEY = "gamebeast:anonymous-id";
const SESSION_KEY = "gamebeast:session";

export interface Identity {
  distinctId: string;
  /** True when the id was generated by the SDK rather than supplied by the developer. */
  isAnonymous: boolean;
}

/**
 * The browser's anonymous id, generated once and kept in `localStorage` so the same browser reports
 * as the same user across visits. It is kept even while an identified user is active, so logging
 * out returns to the same anonymous user.
 */
export function anonymousIdentity(storage: SafeStorage): Identity {
  let stored = storage.getString(ANONYMOUS_ID_KEY);
  if (normalizeDistinctId(stored) === undefined) {
    stored = uuidv4();
    storage.setString(ANONYMOUS_ID_KEY, stored);
  }
  return { distinctId: stored as string, isAnonymous: true };
}

interface StoredSession {
  id: string;
  lastActivityAt: number;
}

/**
 * Session ids group markers into visits. A session is shared by every tab of the origin and ends
 * after `timeoutMs` without activity, so a multi-page site reports one session per visit rather
 * than one per page load.
 */
export class SessionTracker {
  private current: StoredSession;

  constructor(
    private readonly storage: SafeStorage,
    private readonly timeoutMs: number,
    private readonly now: () => number = Date.now
  ) {
    this.current = this.resume() ?? this.start();
  }

  /** The active session id, rotating it first if the session has timed out. */
  touch(): string {
    const time = this.now();
    // Another tab may have extended or rotated the shared session since we last looked.
    const shared = this.storage.getJson<StoredSession>(SESSION_KEY);
    if (isStoredSession(shared) && shared.lastActivityAt > this.current.lastActivityAt) {
      this.current = shared;
    }
    if (this.timeoutMs > 0 && time - this.current.lastActivityAt >= this.timeoutMs) {
      this.current = this.start();
    } else {
      this.current = { id: this.current.id, lastActivityAt: time };
      this.storage.setJson(SESSION_KEY, this.current);
    }
    return this.current.id;
  }

  get id(): string {
    return this.current.id;
  }

  private resume(): StoredSession | undefined {
    const stored = this.storage.getJson<StoredSession>(SESSION_KEY);
    if (!isStoredSession(stored)) return undefined;
    if (this.timeoutMs > 0 && this.now() - stored.lastActivityAt >= this.timeoutMs)
      return undefined;
    return stored;
  }

  private start(): StoredSession {
    const session = { id: uuidv4(), lastActivityAt: this.now() };
    this.storage.setJson(SESSION_KEY, session);
    return session;
  }
}

function isStoredSession(value: unknown): value is StoredSession {
  return (
    typeof value === "object" &&
    value !== null &&
    typeof (value as StoredSession).id === "string" &&
    (value as StoredSession).id.length > 0 &&
    typeof (value as StoredSession).lastActivityAt === "number"
  );
}
